// Generated by CIRCT firtool-1.62.1
module MaxFinder3(	// \\src\\main\\scala\\MaxFinder.scala:36:7
  input        clock,	// \\src\\main\\scala\\MaxFinder.scala:36:7
               reset,	// \\src\\main\\scala\\MaxFinder.scala:36:7
  input  [7:0] io_in_0,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_1,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_2,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_3,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_4,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_5,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_6,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_7,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_8,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_9,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_10,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_11,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_12,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_13,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_14,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_15,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_16,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_17,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_18,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_19,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_20,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_21,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_22,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_23,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_24,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_25,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_26,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_27,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_28,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_29,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_30,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_31,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_32,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_33,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_34,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_35,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_36,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_37,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_38,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_39,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_40,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_41,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_42,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_43,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_44,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_45,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_46,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_47,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_48,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_49,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_50,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_51,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_52,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_53,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_54,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_55,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_56,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_57,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_58,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_59,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_60,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_61,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_62,	// \\src\\main\\scala\\MaxFinder.scala:37:14
               io_in_63,	// \\src\\main\\scala\\MaxFinder.scala:37:14
  output [7:0] io_max,	// \\src\\main\\scala\\MaxFinder.scala:37:14
  output [5:0] io_index	// \\src\\main\\scala\\MaxFinder.scala:37:14
);

  wire       _resFinal_T = io_in_0 > io_in_1;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_1_0 = _resFinal_T ? io_in_0 : io_in_1;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_2 = io_in_2 > io_in_3;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_3_0 = _resFinal_T_2 ? io_in_2 : io_in_3;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_4 = io_in_4 > io_in_5;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_5_0 = _resFinal_T_4 ? io_in_4 : io_in_5;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_6 = io_in_6 > io_in_7;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_7_0 = _resFinal_T_6 ? io_in_6 : io_in_7;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_8 = io_in_8 > io_in_9;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_9_0 = _resFinal_T_8 ? io_in_8 : io_in_9;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_10 = io_in_10 > io_in_11;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_11_0 = _resFinal_T_10 ? io_in_10 : io_in_11;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_12 = io_in_12 > io_in_13;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_13_0 = _resFinal_T_12 ? io_in_12 : io_in_13;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_14 = io_in_14 > io_in_15;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_15_0 = _resFinal_T_14 ? io_in_14 : io_in_15;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_16 = io_in_16 > io_in_17;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_17_0 = _resFinal_T_16 ? io_in_16 : io_in_17;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_18 = io_in_18 > io_in_19;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_19_0 = _resFinal_T_18 ? io_in_18 : io_in_19;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_20 = io_in_20 > io_in_21;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_21_0 = _resFinal_T_20 ? io_in_20 : io_in_21;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_22 = io_in_22 > io_in_23;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_23_0 = _resFinal_T_22 ? io_in_22 : io_in_23;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_24 = io_in_24 > io_in_25;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_25_0 = _resFinal_T_24 ? io_in_24 : io_in_25;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_26 = io_in_26 > io_in_27;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_27_0 = _resFinal_T_26 ? io_in_26 : io_in_27;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_28 = io_in_28 > io_in_29;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_29_0 = _resFinal_T_28 ? io_in_28 : io_in_29;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_30 = io_in_30 > io_in_31;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_31_0 = _resFinal_T_30 ? io_in_30 : io_in_31;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_32 = io_in_32 > io_in_33;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_33_0 = _resFinal_T_32 ? io_in_32 : io_in_33;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_34 = io_in_34 > io_in_35;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_35_0 = _resFinal_T_34 ? io_in_34 : io_in_35;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_36 = io_in_36 > io_in_37;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_37_0 = _resFinal_T_36 ? io_in_36 : io_in_37;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_38 = io_in_38 > io_in_39;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_39_0 = _resFinal_T_38 ? io_in_38 : io_in_39;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_40 = io_in_40 > io_in_41;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_41_0 = _resFinal_T_40 ? io_in_40 : io_in_41;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_42 = io_in_42 > io_in_43;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_43_0 = _resFinal_T_42 ? io_in_42 : io_in_43;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_44 = io_in_44 > io_in_45;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_45_0 = _resFinal_T_44 ? io_in_44 : io_in_45;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_46 = io_in_46 > io_in_47;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_47_0 = _resFinal_T_46 ? io_in_46 : io_in_47;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_48 = io_in_48 > io_in_49;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_49_0 = _resFinal_T_48 ? io_in_48 : io_in_49;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_50 = io_in_50 > io_in_51;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_51_0 = _resFinal_T_50 ? io_in_50 : io_in_51;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_52 = io_in_52 > io_in_53;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_53_0 = _resFinal_T_52 ? io_in_52 : io_in_53;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_54 = io_in_54 > io_in_55;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_55_0 = _resFinal_T_54 ? io_in_54 : io_in_55;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_56 = io_in_56 > io_in_57;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_57_0 = _resFinal_T_56 ? io_in_56 : io_in_57;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_58 = io_in_58 > io_in_59;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_59_0 = _resFinal_T_58 ? io_in_58 : io_in_59;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_60 = io_in_60 > io_in_61;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_61_0 = _resFinal_T_60 ? io_in_60 : io_in_61;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_62 = io_in_62 > io_in_63;	// \\src\\main\\scala\\MaxFinder.scala:49:16
  wire [7:0] _resFinal_T_63_0 = _resFinal_T_62 ? io_in_62 : io_in_63;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_64 = _resFinal_T_1_0 > _resFinal_T_3_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_65_0 = _resFinal_T_64 ? _resFinal_T_1_0 : _resFinal_T_3_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_66 = _resFinal_T_5_0 > _resFinal_T_7_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_67_0 = _resFinal_T_66 ? _resFinal_T_5_0 : _resFinal_T_7_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_68 = _resFinal_T_9_0 > _resFinal_T_11_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_69_0 = _resFinal_T_68 ? _resFinal_T_9_0 : _resFinal_T_11_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_70 = _resFinal_T_13_0 > _resFinal_T_15_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_71_0 = _resFinal_T_70 ? _resFinal_T_13_0 : _resFinal_T_15_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_72 = _resFinal_T_17_0 > _resFinal_T_19_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_73_0 = _resFinal_T_72 ? _resFinal_T_17_0 : _resFinal_T_19_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_74 = _resFinal_T_21_0 > _resFinal_T_23_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_75_0 = _resFinal_T_74 ? _resFinal_T_21_0 : _resFinal_T_23_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_76 = _resFinal_T_25_0 > _resFinal_T_27_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_77_0 = _resFinal_T_76 ? _resFinal_T_25_0 : _resFinal_T_27_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_78 = _resFinal_T_29_0 > _resFinal_T_31_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_79_0 = _resFinal_T_78 ? _resFinal_T_29_0 : _resFinal_T_31_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_80 = _resFinal_T_33_0 > _resFinal_T_35_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_81_0 = _resFinal_T_80 ? _resFinal_T_33_0 : _resFinal_T_35_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_82 = _resFinal_T_37_0 > _resFinal_T_39_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_83_0 = _resFinal_T_82 ? _resFinal_T_37_0 : _resFinal_T_39_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_84 = _resFinal_T_41_0 > _resFinal_T_43_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_85_0 = _resFinal_T_84 ? _resFinal_T_41_0 : _resFinal_T_43_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_86 = _resFinal_T_45_0 > _resFinal_T_47_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_87_0 = _resFinal_T_86 ? _resFinal_T_45_0 : _resFinal_T_47_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_88 = _resFinal_T_49_0 > _resFinal_T_51_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_89_0 = _resFinal_T_88 ? _resFinal_T_49_0 : _resFinal_T_51_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_90 = _resFinal_T_53_0 > _resFinal_T_55_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_91_0 = _resFinal_T_90 ? _resFinal_T_53_0 : _resFinal_T_55_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_92 = _resFinal_T_57_0 > _resFinal_T_59_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_93_0 = _resFinal_T_92 ? _resFinal_T_57_0 : _resFinal_T_59_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_94 = _resFinal_T_61_0 > _resFinal_T_63_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_95_0 = _resFinal_T_94 ? _resFinal_T_61_0 : _resFinal_T_63_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_96 = _resFinal_T_65_0 > _resFinal_T_67_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_97_0 = _resFinal_T_96 ? _resFinal_T_65_0 : _resFinal_T_67_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_98 = _resFinal_T_69_0 > _resFinal_T_71_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_99_0 = _resFinal_T_98 ? _resFinal_T_69_0 : _resFinal_T_71_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_100 = _resFinal_T_73_0 > _resFinal_T_75_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_101_0 = _resFinal_T_100 ? _resFinal_T_73_0 : _resFinal_T_75_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_102 = _resFinal_T_77_0 > _resFinal_T_79_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_103_0 = _resFinal_T_102 ? _resFinal_T_77_0 : _resFinal_T_79_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_104 = _resFinal_T_81_0 > _resFinal_T_83_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_105_0 = _resFinal_T_104 ? _resFinal_T_81_0 : _resFinal_T_83_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_106 = _resFinal_T_85_0 > _resFinal_T_87_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_107_0 = _resFinal_T_106 ? _resFinal_T_85_0 : _resFinal_T_87_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_108 = _resFinal_T_89_0 > _resFinal_T_91_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_109_0 = _resFinal_T_108 ? _resFinal_T_89_0 : _resFinal_T_91_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_110 = _resFinal_T_93_0 > _resFinal_T_95_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_111_0 = _resFinal_T_110 ? _resFinal_T_93_0 : _resFinal_T_95_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_112 = _resFinal_T_97_0 > _resFinal_T_99_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_113_0 = _resFinal_T_112 ? _resFinal_T_97_0 : _resFinal_T_99_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_114 = _resFinal_T_101_0 > _resFinal_T_103_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_115_0 = _resFinal_T_114 ? _resFinal_T_101_0 : _resFinal_T_103_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_116 = _resFinal_T_105_0 > _resFinal_T_107_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_117_0 = _resFinal_T_116 ? _resFinal_T_105_0 : _resFinal_T_107_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_118 = _resFinal_T_109_0 > _resFinal_T_111_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_119_0 = _resFinal_T_118 ? _resFinal_T_109_0 : _resFinal_T_111_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_120 = _resFinal_T_113_0 > _resFinal_T_115_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_121_0 = _resFinal_T_120 ? _resFinal_T_113_0 : _resFinal_T_115_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_122 = _resFinal_T_117_0 > _resFinal_T_119_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire [7:0] _resFinal_T_123_0 = _resFinal_T_122 ? _resFinal_T_117_0 : _resFinal_T_119_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  wire       _resFinal_T_124 = _resFinal_T_121_0 > _resFinal_T_123_0;	// \\src\\main\\scala\\MaxFinder.scala:49:{10,16}
  assign io_max = _resFinal_T_124 ? _resFinal_T_121_0 : _resFinal_T_123_0;	// \\src\\main\\scala\\MaxFinder.scala:36:7, :49:{10,16}
  assign io_index =
    _resFinal_T_124
      ? (_resFinal_T_120
           ? (_resFinal_T_112
                ? (_resFinal_T_96
                     ? (_resFinal_T_64 ? {5'h0, ~_resFinal_T} : {5'h1, ~_resFinal_T_2})
                     : _resFinal_T_66 ? {5'h2, ~_resFinal_T_4} : {5'h3, ~_resFinal_T_6})
                : _resFinal_T_98
                    ? (_resFinal_T_68 ? {5'h4, ~_resFinal_T_8} : {5'h5, ~_resFinal_T_10})
                    : _resFinal_T_70 ? {5'h6, ~_resFinal_T_12} : {5'h7, ~_resFinal_T_14})
           : _resFinal_T_114
               ? (_resFinal_T_100
                    ? (_resFinal_T_72 ? {5'h8, ~_resFinal_T_16} : {5'h9, ~_resFinal_T_18})
                    : _resFinal_T_74 ? {5'hA, ~_resFinal_T_20} : {5'hB, ~_resFinal_T_22})
               : _resFinal_T_102
                   ? (_resFinal_T_76 ? {5'hC, ~_resFinal_T_24} : {5'hD, ~_resFinal_T_26})
                   : _resFinal_T_78 ? {5'hE, ~_resFinal_T_28} : {5'hF, ~_resFinal_T_30})
      : _resFinal_T_122
          ? (_resFinal_T_116
               ? (_resFinal_T_104
                    ? (_resFinal_T_80
                         ? {5'h10, ~_resFinal_T_32}
                         : {5'h11, ~_resFinal_T_34})
                    : _resFinal_T_82
                        ? {5'h12, ~_resFinal_T_36}
                        : {5'h13, ~_resFinal_T_38})
               : _resFinal_T_106
                   ? (_resFinal_T_84
                        ? {5'h14, ~_resFinal_T_40}
                        : {5'h15, ~_resFinal_T_42})
                   : _resFinal_T_86 ? {5'h16, ~_resFinal_T_44} : {5'h17, ~_resFinal_T_46})
          : _resFinal_T_118
              ? (_resFinal_T_108
                   ? (_resFinal_T_88
                        ? {5'h18, ~_resFinal_T_48}
                        : {5'h19, ~_resFinal_T_50})
                   : _resFinal_T_90 ? {5'h1A, ~_resFinal_T_52} : {5'h1B, ~_resFinal_T_54})
              : _resFinal_T_110
                  ? (_resFinal_T_92 ? {5'h1C, ~_resFinal_T_56} : {5'h1D, ~_resFinal_T_58})
                  : _resFinal_T_94 ? {5'h1E, ~_resFinal_T_60} : {5'h1F, ~_resFinal_T_62};	// \\src\\main\\scala\\MaxFinder.scala:36:7, :49:{10,16}
endmodule

