// Generated by CIRCT firtool-1.62.1
module MaxFinder2(	// \\src\\main\\scala\\MaxFinder.scala:17:7
  input        clock,	// \\src\\main\\scala\\MaxFinder.scala:17:7
               reset,	// \\src\\main\\scala\\MaxFinder.scala:17:7
  input  [7:0] io_in_0,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_1,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_2,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_3,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_4,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_5,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_6,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_7,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_8,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_9,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_10,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_11,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_12,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_13,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_14,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_15,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_16,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_17,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_18,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_19,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_20,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_21,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_22,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_23,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_24,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_25,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_26,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_27,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_28,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_29,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_30,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_31,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_32,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_33,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_34,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_35,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_36,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_37,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_38,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_39,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_40,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_41,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_42,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_43,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_44,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_45,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_46,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_47,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_48,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_49,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_50,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_51,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_52,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_53,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_54,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_55,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_56,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_57,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_58,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_59,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_60,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_61,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_62,	// \\src\\main\\scala\\MaxFinder.scala:18:14
               io_in_63,	// \\src\\main\\scala\\MaxFinder.scala:18:14
  output [7:0] io_max,	// \\src\\main\\scala\\MaxFinder.scala:18:14
  output [5:0] io_index	// \\src\\main\\scala\\MaxFinder.scala:18:14
);

  wire       _res_T_2 = io_in_0 > io_in_1;	// \\src\\main\\scala\\MaxFinder.scala:27:24
  wire [7:0] _res_T_1 = _res_T_2 ? io_in_0 : io_in_1;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_6 = _res_T_1 > io_in_2;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_5 = _res_T_6 ? _res_T_1 : io_in_2;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_10 = _res_T_5 > io_in_3;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_9 = _res_T_10 ? _res_T_5 : io_in_3;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_14 = _res_T_9 > io_in_4;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_13 = _res_T_14 ? _res_T_9 : io_in_4;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_18 = _res_T_13 > io_in_5;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_17 = _res_T_18 ? _res_T_13 : io_in_5;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_22 = _res_T_17 > io_in_6;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_21 = _res_T_22 ? _res_T_17 : io_in_6;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_26 = _res_T_21 > io_in_7;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_25 = _res_T_26 ? _res_T_21 : io_in_7;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_30 = _res_T_25 > io_in_8;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_29 = _res_T_30 ? _res_T_25 : io_in_8;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_34 = _res_T_29 > io_in_9;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_33 = _res_T_34 ? _res_T_29 : io_in_9;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_38 = _res_T_33 > io_in_10;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_37 = _res_T_38 ? _res_T_33 : io_in_10;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_42 = _res_T_37 > io_in_11;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_41 = _res_T_42 ? _res_T_37 : io_in_11;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_46 = _res_T_41 > io_in_12;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_45 = _res_T_46 ? _res_T_41 : io_in_12;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_50 = _res_T_45 > io_in_13;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_49 = _res_T_50 ? _res_T_45 : io_in_13;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_54 = _res_T_49 > io_in_14;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_53 = _res_T_54 ? _res_T_49 : io_in_14;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_58 = _res_T_53 > io_in_15;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_57 = _res_T_58 ? _res_T_53 : io_in_15;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_62 = _res_T_57 > io_in_16;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_61 = _res_T_62 ? _res_T_57 : io_in_16;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_66 = _res_T_61 > io_in_17;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_65 = _res_T_66 ? _res_T_61 : io_in_17;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_70 = _res_T_65 > io_in_18;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_69 = _res_T_70 ? _res_T_65 : io_in_18;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_74 = _res_T_69 > io_in_19;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_73 = _res_T_74 ? _res_T_69 : io_in_19;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_78 = _res_T_73 > io_in_20;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_77 = _res_T_78 ? _res_T_73 : io_in_20;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_82 = _res_T_77 > io_in_21;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_81 = _res_T_82 ? _res_T_77 : io_in_21;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_86 = _res_T_81 > io_in_22;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_85 = _res_T_86 ? _res_T_81 : io_in_22;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_90 = _res_T_85 > io_in_23;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_89 = _res_T_90 ? _res_T_85 : io_in_23;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_94 = _res_T_89 > io_in_24;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_93 = _res_T_94 ? _res_T_89 : io_in_24;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_98 = _res_T_93 > io_in_25;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_97 = _res_T_98 ? _res_T_93 : io_in_25;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_102 = _res_T_97 > io_in_26;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_101 = _res_T_102 ? _res_T_97 : io_in_26;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_106 = _res_T_101 > io_in_27;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_105 = _res_T_106 ? _res_T_101 : io_in_27;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_110 = _res_T_105 > io_in_28;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_109 = _res_T_110 ? _res_T_105 : io_in_28;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_114 = _res_T_109 > io_in_29;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_113 = _res_T_114 ? _res_T_109 : io_in_29;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_118 = _res_T_113 > io_in_30;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_117 = _res_T_118 ? _res_T_113 : io_in_30;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_122 = _res_T_117 > io_in_31;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_121 = _res_T_122 ? _res_T_117 : io_in_31;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_126 = _res_T_121 > io_in_32;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_125 = _res_T_126 ? _res_T_121 : io_in_32;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_130 = _res_T_125 > io_in_33;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_129 = _res_T_130 ? _res_T_125 : io_in_33;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_134 = _res_T_129 > io_in_34;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_133 = _res_T_134 ? _res_T_129 : io_in_34;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_138 = _res_T_133 > io_in_35;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_137 = _res_T_138 ? _res_T_133 : io_in_35;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_142 = _res_T_137 > io_in_36;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_141 = _res_T_142 ? _res_T_137 : io_in_36;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_146 = _res_T_141 > io_in_37;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_145 = _res_T_146 ? _res_T_141 : io_in_37;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_150 = _res_T_145 > io_in_38;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_149 = _res_T_150 ? _res_T_145 : io_in_38;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_154 = _res_T_149 > io_in_39;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_153 = _res_T_154 ? _res_T_149 : io_in_39;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_158 = _res_T_153 > io_in_40;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_157 = _res_T_158 ? _res_T_153 : io_in_40;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_162 = _res_T_157 > io_in_41;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_161 = _res_T_162 ? _res_T_157 : io_in_41;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_166 = _res_T_161 > io_in_42;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_165 = _res_T_166 ? _res_T_161 : io_in_42;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_170 = _res_T_165 > io_in_43;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_169 = _res_T_170 ? _res_T_165 : io_in_43;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_174 = _res_T_169 > io_in_44;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_173 = _res_T_174 ? _res_T_169 : io_in_44;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_178 = _res_T_173 > io_in_45;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_177 = _res_T_178 ? _res_T_173 : io_in_45;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_182 = _res_T_177 > io_in_46;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_181 = _res_T_182 ? _res_T_177 : io_in_46;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_186 = _res_T_181 > io_in_47;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_185 = _res_T_186 ? _res_T_181 : io_in_47;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_190 = _res_T_185 > io_in_48;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_189 = _res_T_190 ? _res_T_185 : io_in_48;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_194 = _res_T_189 > io_in_49;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_193 = _res_T_194 ? _res_T_189 : io_in_49;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_198 = _res_T_193 > io_in_50;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_197 = _res_T_198 ? _res_T_193 : io_in_50;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_202 = _res_T_197 > io_in_51;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_201 = _res_T_202 ? _res_T_197 : io_in_51;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_206 = _res_T_201 > io_in_52;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_205 = _res_T_206 ? _res_T_201 : io_in_52;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_210 = _res_T_205 > io_in_53;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_209 = _res_T_210 ? _res_T_205 : io_in_53;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_214 = _res_T_209 > io_in_54;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_213 = _res_T_214 ? _res_T_209 : io_in_54;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_218 = _res_T_213 > io_in_55;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_217 = _res_T_218 ? _res_T_213 : io_in_55;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_222 = _res_T_217 > io_in_56;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_221 = _res_T_222 ? _res_T_217 : io_in_56;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_226 = _res_T_221 > io_in_57;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_225 = _res_T_226 ? _res_T_221 : io_in_57;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_230 = _res_T_225 > io_in_58;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_229 = _res_T_230 ? _res_T_225 : io_in_58;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_234 = _res_T_229 > io_in_59;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_233 = _res_T_234 ? _res_T_229 : io_in_59;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_238 = _res_T_233 > io_in_60;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_237 = _res_T_238 ? _res_T_233 : io_in_60;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_242 = _res_T_237 > io_in_61;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_241 = _res_T_242 ? _res_T_237 : io_in_61;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_246 = _res_T_241 > io_in_62;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire [7:0] _res_T_245 = _res_T_246 ? _res_T_241 : io_in_62;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  wire       _res_T_249 = _res_T_245 > io_in_63;	// \\src\\main\\scala\\MaxFinder.scala:27:{18,24}
  assign io_max = _res_T_249 ? _res_T_245 : io_in_63;	// \\src\\main\\scala\\MaxFinder.scala:17:7, :27:{18,24}
  assign io_index =
    _res_T_249
      ? (_res_T_246
           ? (_res_T_242
                ? (_res_T_238
                     ? (_res_T_234
                          ? (_res_T_230
                               ? (_res_T_226
                                    ? (_res_T_222
                                         ? (_res_T_218
                                              ? (_res_T_214
                                                   ? (_res_T_210
                                                        ? (_res_T_206
                                                             ? (_res_T_202
                                                                  ? (_res_T_198
                                                                       ? (_res_T_194
                                                                            ? (_res_T_190
                                                                                 ? (_res_T_186
                                                                                      ? (_res_T_182
                                                                                           ? (_res_T_178
                                                                                                ? (_res_T_174
                                                                                                     ? (_res_T_170
                                                                                                          ? (_res_T_166
                                                                                                               ? (_res_T_162
                                                                                                                    ? (_res_T_158
                                                                                                                         ? (_res_T_154
                                                                                                                              ? (_res_T_150
                                                                                                                                   ? (_res_T_146
                                                                                                                                        ? (_res_T_142
                                                                                                                                             ? (_res_T_138
                                                                                                                                                  ? (_res_T_134
                                                                                                                                                       ? (_res_T_130
                                                                                                                                                            ? (_res_T_126
                                                                                                                                                                 ? {1'h0,
                                                                                                                                                                    _res_T_122
                                                                                                                                                                      ? (_res_T_118
                                                                                                                                                                           ? (_res_T_114
                                                                                                                                                                                ? (_res_T_110
                                                                                                                                                                                     ? (_res_T_106
                                                                                                                                                                                          ? (_res_T_102
                                                                                                                                                                                               ? (_res_T_98
                                                                                                                                                                                                    ? (_res_T_94
                                                                                                                                                                                                         ? (_res_T_90
                                                                                                                                                                                                              ? (_res_T_86
                                                                                                                                                                                                                   ? (_res_T_82
                                                                                                                                                                                                                        ? (_res_T_78
                                                                                                                                                                                                                             ? (_res_T_74
                                                                                                                                                                                                                                  ? (_res_T_70
                                                                                                                                                                                                                                       ? (_res_T_66
                                                                                                                                                                                                                                            ? (_res_T_62
                                                                                                                                                                                                                                                 ? {1'h0,
                                                                                                                                                                                                                                                    _res_T_58
                                                                                                                                                                                                                                                      ? (_res_T_54
                                                                                                                                                                                                                                                           ? (_res_T_50
                                                                                                                                                                                                                                                                ? (_res_T_46
                                                                                                                                                                                                                                                                     ? (_res_T_42
                                                                                                                                                                                                                                                                          ? (_res_T_38
                                                                                                                                                                                                                                                                               ? (_res_T_34
                                                                                                                                                                                                                                                                                    ? (_res_T_30
                                                                                                                                                                                                                                                                                         ? {1'h0,
                                                                                                                                                                                                                                                                                            _res_T_26
                                                                                                                                                                                                                                                                                              ? (_res_T_22
                                                                                                                                                                                                                                                                                                   ? (_res_T_18
                                                                                                                                                                                                                                                                                                        ? (_res_T_14
                                                                                                                                                                                                                                                                                                             ? {1'h0,
                                                                                                                                                                                                                                                                                                                _res_T_10
                                                                                                                                                                                                                                                                                                                  ? (_res_T_6
                                                                                                                                                                                                                                                                                                                       ? {1'h0,
                                                                                                                                                                                                                                                                                                                          ~_res_T_2}
                                                                                                                                                                                                                                                                                                                       : 2'h2)
                                                                                                                                                                                                                                                                                                                  : 2'h3}
                                                                                                                                                                                                                                                                                                             : 3'h4)
                                                                                                                                                                                                                                                                                                        : 3'h5)
                                                                                                                                                                                                                                                                                                   : 3'h6)
                                                                                                                                                                                                                                                                                              : 3'h7}
                                                                                                                                                                                                                                                                                         : 4'h8)
                                                                                                                                                                                                                                                                                    : 4'h9)
                                                                                                                                                                                                                                                                               : 4'hA)
                                                                                                                                                                                                                                                                          : 4'hB)
                                                                                                                                                                                                                                                                     : 4'hC)
                                                                                                                                                                                                                                                                : 4'hD)
                                                                                                                                                                                                                                                           : 4'hE)
                                                                                                                                                                                                                                                      : 4'hF}
                                                                                                                                                                                                                                                 : 5'h10)
                                                                                                                                                                                                                                            : 5'h11)
                                                                                                                                                                                                                                       : 5'h12)
                                                                                                                                                                                                                                  : 5'h13)
                                                                                                                                                                                                                             : 5'h14)
                                                                                                                                                                                                                        : 5'h15)
                                                                                                                                                                                                                   : 5'h16)
                                                                                                                                                                                                              : 5'h17)
                                                                                                                                                                                                         : 5'h18)
                                                                                                                                                                                                    : 5'h19)
                                                                                                                                                                                               : 5'h1A)
                                                                                                                                                                                          : 5'h1B)
                                                                                                                                                                                     : 5'h1C)
                                                                                                                                                                                : 5'h1D)
                                                                                                                                                                           : 5'h1E)
                                                                                                                                                                      : 5'h1F}
                                                                                                                                                                 : 6'h20)
                                                                                                                                                            : 6'h21)
                                                                                                                                                       : 6'h22)
                                                                                                                                                  : 6'h23)
                                                                                                                                             : 6'h24)
                                                                                                                                        : 6'h25)
                                                                                                                                   : 6'h26)
                                                                                                                              : 6'h27)
                                                                                                                         : 6'h28)
                                                                                                                    : 6'h29)
                                                                                                               : 6'h2A)
                                                                                                          : 6'h2B)
                                                                                                     : 6'h2C)
                                                                                                : 6'h2D)
                                                                                           : 6'h2E)
                                                                                      : 6'h2F)
                                                                                 : 6'h30)
                                                                            : 6'h31)
                                                                       : 6'h32)
                                                                  : 6'h33)
                                                             : 6'h34)
                                                        : 6'h35)
                                                   : 6'h36)
                                              : 6'h37)
                                         : 6'h38)
                                    : 6'h39)
                               : 6'h3A)
                          : 6'h3B)
                     : 6'h3C)
                : 6'h3D)
           : 6'h3E)
      : 6'h3F;	// \\src\\main\\scala\\MaxFinder.scala:17:7, :27:24, :28:18
endmodule

